ETFE-2469: Add trader name/ERN and 'change trader link' to every page…
hmrc/emcs-tfe-cancel-movement-frontend pull request #21
Opened 2023-11-16 16:50 UTC by nickg-hmrc

…, if user has multiple ERNs on their login

2023-11-21 10:44 UTC, LewisMitchell requested changes
> * Config key `play.http.secret.key` can be removed from [test/resources/application.conf](https://github.com/hmrc/emcs-tfe-cancel-movement-frontend/blob/ETFE-2469/test/resources/application.conf#L17). This is already provided by Bootstrap

Could you address this as well please?

2023-11-21 10:44 UTC, LewisMitchell commented on app/featureswitch/core/config/FeatureSwitchingModule.scala
> +  override val configName: String = "features.stub-get-trader-known-facts"
This config will need to be set appropriately for the QA, Staging and Production environment

2023-11-21 10:44 UTC, LewisMitchell commented on conf/application.conf
> +    }
emcs-tfe-reference-data is the same as reference-data further up, so either `emcs-tfe-reference-data` or `reference-data`  can be removed

2023-11-21 10:44 UTC, LewisMitchell commented on test/connectors/referenceData/GetTraderKnownFactsConnectorSpec.scala
> +  "check" - {
```suggestion
  "getTraderKnownFacts" - {
```

2023-11-21 10:44 UTC, LewisMitchell commented on test/views/components/ActiveTraderSpec.scala
> +        }
Could these be collapsed into one test? At the moment, it has to generate 3 identical HTML components. If it were collapsed into one test you could do something like:
```suggestion
        "render the correct HTML" in {

          val html = activeTrader(Some(traderInfo), appConfig)
          val doc = Jsoup.parse(html.toString())
          val link =  doc.select(linkSelector).first

          doc.select(divSelector).size mustEqual 1
          doc.select(titleSelector).text mustEqual s"$traderName ($ern)"
          link.attr("href") mustEqual "http://localhost:8310/emcs-tfe"
          link.text mustEqual messagesForLanguage.changeTraderType
        }
```

2023-11-22 16:21 UTC, nickg-hmrc commented on app/featureswitch/core/config/FeatureSwitchingModule.scala
> +  override val configName: String = "features.stub-get-trader-known-facts"
I've made some PR's here:
https://github.com/hmrc/app-config-base/pull/9706
https://github.com/hmrc/app-config-production/pull/20418
https://github.com/hmrc/app-config-qa/pull/20653
https://github.com/hmrc/app-config-staging/pull/14212

2023-11-22 17:01 UTC, LewisMitchell requested changes

2023-11-22 17:01 UTC, LewisMitchell commented on app/connectors/referenceData/GetTraderKnownFactsHttpParser.scala
> +              Left(JsonValidationError)
Looks to be a missing test for this scenario

2023-11-22 17:01 UTC, LewisMitchell commented on app/connectors/referenceData/GetTraderKnownFactsConnector.scala
Could you add an integration test for this, please?

2023-11-22 17:28 UTC, LewisMitchell approved these changes

2023-11-22 17:29 UTC, merged